### ISSUE TITLE
Click and drag over action buttons causes core dump

### ISSUE THREAD

**Issue by synackray** [M4cs/pystickynote#2]
### Steps to Reproduce
1. Create a note by running `pystickynote create test1`.
2. Type any test in the note field
3. Left-click and drag any action button such as `Save` or `Exit`.

### Expected Behavior
No behavior, the application should not have a response to left-click and drag over action buttons.

### Observed Behavior
An error is generated regarding `mouse_offset` and the application is closed forcibly. 
```
$ pystickynote create test4
Traceback (most recent call last):
  File "/home/user/Documents/Projects/pystickynote/lib/python3.6/site-packages/PySimpleGUIQt/PySimpleGUIQt.py", line 3664, in eventFilter
    x_w = self.mouse_offset.x()
AttributeError: 'QT_QMainWindowClass' object has no attribute 'mouse_offset'
Aborted (core dumped)
```

**Comment by M4cs** [comment]
Thanks Ill look into this today

**Comment by M4cs** [comment]
What platform are you on

**Comment by synackray** [comment]
This was tested on Linux Mint. Thanks!

```
$ cat /etc/linuxmint/info 
RELEASE=19.2
CODENAME=tina
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19.2 Tina"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_tina_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 19.2 Cinnamon
```

**Comment by M4cs** [comment]
Fixed this on the newest commit before I merged your PR
